#!/usr/bin/env bash
# display information about subdomains


display_info() {
    domain="$1"
    subdomain="$2"
    dig_output=$(dig "$subdomain.$domain" +noall +answer)
    record=$(echo "$dig_output" | awk '{print $4}')
    destination=$(echo "$dig_output" | awk '{print $5}')
    echo "The subdomain $subdomain is a $record record and points to $destination"
}

if [ -z "$1" ]; then
    echo "Error: domain argument is required"
    exit 1
fi

if [ -z "$2" ]; then
    for subdomain in "www" "lb-01" "web-01" "web-02"; do
        display_info "$1" "$subdomain"
    done
else
    display_info "$1" "$2"
fi

