#!/usr/bin/env bash

# Check the number of parameters
if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

#Get the parameters
file_path=$1
ip=$2
username=$3
ssh_key_path=$4

#Disable strict host
ssh -o StrictHostKeyChecking=no "$username"@"$ip"
#Transfer the file
scp -i "$ssh_key_path $file_path" "$username"@"$ip":~/
