#!/usr/bin/env bash
# Installs and configures Nginx on a new Ubuntu machine

# Install Nginx
sudo apt-get install -y nginx

# Start Nginx
sudo service nginx start

ufw allow 'Nginx HTTP'
# Create an index.html file with the string "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Restart Nginx to apply changes.
sudo service nginx restart
