#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer

# Install software-properties-common and add HAproxy repository
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8

# Update package list and install HAproxy
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*

# Configure HAproxy
sudo tee /etc/haproxy/haproxy.cfg <<EOL
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 289118-web-01 54.208.163.19:80 check 
    server 289118-web-02 54.236.52.141:80 check 
EOL

# Enable HAproxy and start the service
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sudo service haproxy start 

