#!/usr/bin/env bash
# Display "To infinity and beyond" indefinitely
# Display "I hate the kill command" when SIGTERM signal
# Display "Y U no love me?!" when receiving a SIGINT signal
# Delete the file and terminate when receiving a SIGQUIT or SIGTERM


pid_file="/var/run/myscript.pid"
echo "$$" > "$pid_file"

termfunc()
{
	rm "$pid_file"
	exit
}
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command" && termfunc' SIGTERM
trap 'termfunc' SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
