#!/usr/bin/env bash
# Display numbers from 1 to 100
# FizzBuzz if number multiple of 3 and 5
# Fizz if multiple of 3
# Buzz if multiple of 5
# Otherwise displays the number

for i in {1..100}
do
	if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done

