#!/usr/bin/env bash
# Display content of the file "/etc/passwd"

file="/etc/passwd"
while IFS=':' read -r user pass uid gid username homedir shell
do
	echo "The user $user is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $username"
done < "$file"
