#!/usr/bin/env bash
# if 4 "bad luck from China"
# if 9 "bad luck from Japan"
# if 17 "bad luck from Italy"

counter=1

while [ $counter -le 20 ]
do
	echo "$counter"
	case $counter in
		4)
			echo "bad luck from China";;
		9)
			echo "bad luck from Japan";;
		17)
			echo "bad luck from Italy";;
	esac
	((counter++))
done
