#!/usr/bin/env bash
# Display clock from 0 to 12

hours=0

while [ $hours -le 12 ]
do
	echo "Hour: $hours"
	minutes=1
	while [ $minutes -le 59 ]
	do
		echo "$minutes"
		((minutes++))
	done
	((hours++))
done
