#!/usr/bin/env bash
# change addresses

old_host=/etc/hosts
new_host=~/hosts.new

cp $old_host $new_host
sed -i "s/^127[0-9.]*\slocalhost/127.0.0.2 localhost/" $new_host
sed -i "$ a\8.8.8.8 facebook.com" $new_host
cp -f $new_host $old_host
